sonar.projectKey=NaisaTech_chocoTumac
sonar.organization=naisatech
sonar.projectName=chocoTumac
sonar.projectVersion=1.2.0
sonar.sources=.
sonar.exclusions=**/*.sql,**/vendor/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.php.version=7.4