sonar.projectKey=NaisaTech_chocoTumac
sonar.organization=naisatech
sonar.projectName=chocoTumac
sonar.projectVersion=1.2.0
sonar.sources=.
sonar.exclusions=**/*.sql,**/vendor/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.php.version=8.0
# Ignora cobertura porque no usas PHPUnit
sonar.coverage.exclusions=**/*

# Ignora duplicación en todo el código nuevo
sonar.cpd.exclusions=**/*

# Ignora el rating D de fiabilidad en código nuevo
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S1172
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S2259