sonar.projectKey=NaisaTech_chocoTumac
sonar.organization=naisatech
sonar.projectName=chocoTumac
sonar.projectVersion=1.2.0
sonar.sources=.
sonar.exclusions=**/*.sql,**/vendor/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.php.version=8.0

# Ruta del reporte de coverage que genera PHPUnit
sonar.php.coverage.reportPaths=tests/reports/coverage.xml

# Mantén solo las exclusiones de issues si las necesitas
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S1172
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S2259

# Ignora duplicación de código
sonar.cpd.exclusions=**/*